# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Dockerfile.smithery
# Use Node.js 18 LTS on Alpine
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package manifests
COPY package.json package-lock.json ./

# Insert ESM module type into package.json
RUN sed -i '/"version":/a\  "type": "module",' package.json

# Install dependencies, including axios
RUN npm install --production && npm install axios --production

# Copy application source
COPY . .

# Run the MCP server
CMD ["node", "index.js"]
